package com.lexorion.payroll.service;

import static com.lexorion.payroll.api.PayRunDtos.*;
import com.lexorion.payroll.api.PayrollException;
import com.lexorion.payroll.domain.*;
import com.lexorion.payroll.entitlement.PayrollProcessingEntitlementGate;
import com.lexorion.payroll.repository.*;
import java.math.*;
import java.time.Instant;
import java.util.*;
import org.springframework.data.domain.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class PayRunService {
 private static final BigDecimal ZERO=new BigDecimal("0.0000");
 private static final Map<String,String>SORTS=Map.of("payRunKey","payRunKey","periodStart","periodStart","periodEnd","periodEnd","calculationDate","calculationDate","status","status","createdAt","createdAt");
 private final PayrollWorkspaceScope scope;private final PayRunRepository runs;private final PayRunEmployeeRepository runEmployees;private final PayrollEmployeeRepository employees;private final PayrollProcessingEntitlementGate entitlement;
 public PayRunService(PayrollWorkspaceScope s,PayRunRepository r,PayRunEmployeeRepository re,PayrollEmployeeRepository e,PayrollProcessingEntitlementGate g){scope=s;runs=r;runEmployees=re;employees=e;entitlement=g;}
 @Transactional public PayRunResponse create(CreatePayRun request){PayrollWorkspace workspace=scope.locked();String key=key(request.payRunKey());if(request.periodEnd().isBefore(request.periodStart()))throw new PayrollException(400,"periodEnd cannot precede periodStart");if(runs.existsByWorkspaceIdAndPayRunKey(workspace.getId(),key))throw new PayrollException(409,"Pay Run already exists");PayRun run=new PayRun();run.setWorkspace(workspace);run.setPayRunKey(key);run.setPeriodStart(request.periodStart());run.setPeriodEnd(request.periodEnd());run.setCalculationDate(request.calculationDate());run.setCurrency(PayrollEmployeeService.currency(request.currency()));run.setStatus(PayRunStatus.DRAFT);run.setGrossTotal(ZERO);run.setDeductionTotal(ZERO);run.setNetTotal(ZERO);return response(runs.saveAndFlush(run));}
 @Transactional(readOnly=true)public PayRunPage list(int page,int size,String sort,String direction,PayRunStatus status){if(page<0||size<1||size>100)throw new PayrollException(400,"Invalid pagination");String property=SORTS.get(sort);if(property==null)throw new PayrollException(400,"Invalid Pay Run sort field");Sort.Direction order;try{order=Sort.Direction.fromString(direction);}catch(IllegalArgumentException e){throw new PayrollException(400,"Invalid sort direction");}Page<PayRun>result=runs.search(scope.context().workspaceId(),status,PageRequest.of(page,size,Sort.by(order,property).and(Sort.by(Sort.Direction.ASC,"payRunKey"))));return new PayRunPage(result.stream().map(this::response).toList(),page,size,result.getTotalElements(),result.getTotalPages(),sort,order.name().toLowerCase(Locale.ROOT));}
 @Transactional(readOnly=true)public PayRunResponse get(String raw){return response(find(raw));}
 @Transactional(readOnly=true)public List<PayRunEmployeeResponse>employees(String raw){PayRun run=find(raw);return runEmployees.findByPayRunIdOrderByEmployeeCodeAsc(run.getId()).stream().map(this::employeeResponse).toList();}
 @Transactional public PayRunEmployeeResponse addEmployee(String raw,AddPayRunEmployee request){scope.locked();PayRun run=locked(raw);requireStatus(run,PayRunStatus.DRAFT);String code=CompensationService.employeeCode(request.employeeCode());PayrollEmployee employee=employees.findScopedForUpdate(scope.context().workspaceId(),code).orElseThrow(()->new PayrollException(404,"Payroll employee not found"));if(employee.getStatus()!=PayrollStatus.ACTIVE)throw new PayrollException(409,"Payroll employee is not active for calculation");if(runEmployees.existsByPayRunIdAndPayrollEmployeeId(run.getId(),employee.getId()))throw new PayrollException(409,"Employee is already included in Pay Run");PayRunEmployee included=new PayRunEmployee();included.setPayRun(run);included.setPayrollEmployee(employee);included.setEmployeeCode(code);included.setGrossSnapshot(ZERO);included.setDeductionSnapshot(ZERO);included.setNetSnapshot(ZERO);included.setCurrency(run.getCurrency());return employeeResponse(runEmployees.saveAndFlush(included));}
 @Transactional public PayRunResponse finalizeRun(String raw){entitlement.requireProcessing(scope.context());scope.locked();PayRun run=locked(raw);requireStatus(run,PayRunStatus.CALCULATED);List<PayRunEmployee>included=runEmployees.findByPayRunIdOrderByEmployeeCodeAsc(run.getId());if(included.isEmpty())throw new PayrollException(409,"Empty Pay Run cannot be finalized");if(included.stream().anyMatch(e->e.getCalculation()==null))throw new PayrollException(409,"Pay Run contains an incomplete calculation");BigDecimal gross=sum(included.stream().map(PayRunEmployee::getGrossSnapshot).toList()),deductions=sum(included.stream().map(PayRunEmployee::getDeductionSnapshot).toList()),net=sum(included.stream().map(PayRunEmployee::getNetSnapshot).toList());if(gross.compareTo(run.getGrossTotal())!=0||deductions.compareTo(run.getDeductionTotal())!=0||net.compareTo(run.getNetTotal())!=0||net.compareTo(gross.subtract(deductions))!=0)throw new PayrollException(409,"Pay Run totals are inconsistent");run.setStatus(PayRunStatus.FINALIZED);run.setFinalizedAt(Instant.now());return response(runs.saveAndFlush(run));}
 PayRun locked(String raw){return runs.findScopedForUpdate(scope.context().workspaceId(),key(raw)).orElseThrow(()->new PayrollException(404,"Pay Run not found"));}private PayRun find(String raw){return runs.findByWorkspaceIdAndPayRunKey(scope.context().workspaceId(),key(raw)).orElseThrow(()->new PayrollException(404,"Pay Run not found"));}static String key(String raw){String key=raw==null?"":raw.trim().toUpperCase(Locale.ROOT);if(!key.matches("^[A-Z0-9][A-Z0-9._-]{0,63}$"))throw new PayrollException(400,"Invalid Pay Run key");return key;}static void requireStatus(PayRun run,PayRunStatus expected){if(run.getStatus()!=expected)throw new PayrollException(409,"Pay Run must be "+expected);}private BigDecimal sum(List<BigDecimal>values){return values.stream().reduce(ZERO,BigDecimal::add).setScale(4,RoundingMode.HALF_UP);}PayRunResponse response(PayRun r){return new PayRunResponse(r.getPayRunKey(),r.getPeriodStart(),r.getPeriodEnd(),r.getCalculationDate(),r.getCurrency(),r.getStatus(),r.getGrossTotal(),r.getDeductionTotal(),r.getNetTotal(),runEmployees.countByPayRunId(r.getId()),r.getCreatedAt(),r.getUpdatedAt(),r.getFinalizedAt());}PayRunEmployeeResponse employeeResponse(PayRunEmployee e){return new PayRunEmployeeResponse(e.getEmployeeCode(),e.getGrossSnapshot(),e.getDeductionSnapshot(),e.getNetSnapshot(),e.getCurrency(),e.getPayRun().getCalculationDate());}
}
