package com.lexorion.payroll.service;
import static com.lexorion.payroll.api.PayrollHistoryDtos.*;import com.lexorion.payroll.api.PayrollException;import com.lexorion.payroll.domain.*;import com.lexorion.payroll.repository.*;import java.math.BigDecimal;import java.time.LocalDate;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class PayrollHistoryService{
 private final PayrollWorkspaceScope scope;private final PayrollEmployeeRepository employees;private final PayrollLedgerEntryRepository ledger;private final PayRunEmployeeRepository runEmployees;
 public PayrollHistoryService(PayrollWorkspaceScope s,PayrollEmployeeRepository e,PayrollLedgerEntryRepository l,PayRunEmployeeRepository r){scope=s;employees=e;ledger=l;runEmployees=r;}
 @Transactional(readOnly=true)public List<LedgerEntryResponse>ledger(String raw,LocalDate from,LocalDate to,String rawRun,PayrollLedgerEntryType type){String code=requireEmployee(raw);if(from!=null&&to!=null&&to.isBefore(from))throw new PayrollException(400,"toDate cannot precede fromDate");String run=rawRun==null?null:PayRunService.key(rawRun);return ledger.search(scope.context().workspaceId(),code,from,to,run,type).stream().map(this::ledgerResponse).toList();}
 @Transactional(readOnly=true)public List<PayslipResponse>payslips(String raw){String code=requireEmployee(raw);return runEmployees.findFinalizedPayslips(scope.context().workspaceId(),code).stream().map(this::payslip).toList();}
 @Transactional(readOnly=true)public PayslipResponse payslip(String raw,String rawRun){String code=requireEmployee(raw);return payslip(runEmployees.findFinalizedPayslip(scope.context().workspaceId(),code,PayRunService.key(rawRun)).orElseThrow(()->new PayrollException(404,"Finalized payslip not found")));}
 void createLedger(PayRun run,List<PayRunEmployee>included){if(ledger.existsByWorkspaceIdAndPayRunId(run.getWorkspace().getId(),run.getId()))throw new PayrollException(409,"Pay Run ledger already exists");List<PayrollLedgerEntry>entries=new ArrayList<>();for(PayRunEmployee employee:included){for(CalculationLine line:employee.getCalculation().getLines()){if(line.getCalculatedAmount().signum()==0)continue;PayrollLedgerEntryType type=line.getCategory()==ComponentCategory.EARNING?PayrollLedgerEntryType.EARNING:PayrollLedgerEntryType.DEDUCTION;BigDecimal signed=type==PayrollLedgerEntryType.EARNING?line.getCalculatedAmount():line.getCalculatedAmount().negate();String source=source(run,employee,type,line.getComponentKey());entries.add(PayrollLedgerEntry.finalized(run,employee,type,line.getComponentKey(),line.getDisplayName(),signed,source));}if(employee.getNetSnapshot().signum()!=0)entries.add(PayrollLedgerEntry.finalized(run,employee,PayrollLedgerEntryType.NET_PAY,null,"Net pay",employee.getNetSnapshot().negate(),source(run,employee,PayrollLedgerEntryType.NET_PAY,"NET")));}ledger.saveAll(entries);ledger.flush();}
 private String source(PayRun r,PayRunEmployee e,PayrollLedgerEntryType type,String component){return r.getPayRunKey()+":"+e.getEmployeeCode()+":"+type+":"+component;}
 private String requireEmployee(String raw){String code=CompensationService.employeeCode(raw);if(!employees.existsByWorkspaceIdAndEmployeeCode(scope.context().workspaceId(),code))throw new PayrollException(404,"Payroll employee not found");return code;}
 private LedgerEntryResponse ledgerResponse(PayrollLedgerEntry e){return new LedgerEntryResponse(e.getPayrollEmployee().getEmployeeCode(),e.getPayRun().getPayRunKey(),e.getPeriodStart(),e.getPeriodEnd(),e.getEntryDate(),e.getType(),e.getComponentKey(),e.getComponentName(),e.getAmount(),e.getCurrency(),e.getSourceReference(),e.getStatus(),e.getCreatedAt());}
 private PayslipResponse payslip(PayRunEmployee e){PayRun r=e.getPayRun();List<PayslipLine>earnings=new ArrayList<>(),deductions=new ArrayList<>();for(CalculationLine l:e.getCalculation().getLines()){PayslipLine line=new PayslipLine(l.getComponentKey(),l.getDisplayName(),l.getCategory(),l.getCalculatedAmount());if(l.getCategory()==ComponentCategory.EARNING)earnings.add(line);else deductions.add(line);}earnings.sort(Comparator.comparing(PayslipLine::componentKey));deductions.sort(Comparator.comparing(PayslipLine::componentKey));return new PayslipResponse(e.getEmployeeCode(),r.getPayRunKey(),r.getPeriodStart(),r.getPeriodEnd(),r.getCalculationDate(),e.getCurrency(),earnings,deductions,e.getGrossSnapshot(),e.getDeductionSnapshot(),e.getNetSnapshot(),r.getFinalizedAt());}
}
