package com.lexorion.payroll.service;
import static com.lexorion.payroll.api.SalaryTemplateDtos.*;import com.lexorion.payroll.api.PayrollException;import com.lexorion.payroll.api.CompensationDtos.ProfileResponse;import com.lexorion.payroll.domain.*;import com.lexorion.payroll.repository.*;import java.math.*;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.*;
@Service public class SalaryTemplateService{
 private final PayrollWorkspaceScope scope;private final SalaryTemplateRepository templates;private final ComponentDefinitionRepository definitions;private final SalaryTemplateVersionRepository versions;private final CompensationService compensation;
 public SalaryTemplateService(PayrollWorkspaceScope s,SalaryTemplateRepository t,ComponentDefinitionRepository d,SalaryTemplateVersionRepository v,CompensationService c){scope=s;templates=t;definitions=d;versions=v;compensation=c;}
 @Transactional(readOnly=true)public List<SalaryTemplateResponse>list(){return templates.findByWorkspaceIdOrderByTemplateKeyAsc(scope.context().workspaceId()).stream().map(this::response).toList();}
 @Transactional(readOnly=true)public SalaryTemplateResponse get(String raw){return response(find(raw));}
 @Transactional public SalaryTemplateResponse create(CreateSalaryTemplate r){PayrollWorkspace workspace=scope.locked();String key=key(r.templateKey());if(templates.existsByWorkspaceIdAndTemplateKey(workspace.getId(),key))throw new PayrollException(409,"Salary template key already exists");validateDates(r.effectiveFrom(),r.effectiveTo());SalaryTemplate t=new SalaryTemplate();t.setWorkspace(workspace);t.setTemplateKey(key);apply(t,r.displayName(),r.description(),r.currency(),r.payFrequency(),r.status(),r.effectiveFrom(),r.effectiveTo(),r.components());SalaryTemplate saved=templates.saveAndFlush(t);createInitialVersion(saved);return response(saved);}
 @Transactional public SalaryTemplateResponse update(String raw,UpdateSalaryTemplate r){scope.locked();SalaryTemplate t=find(raw);String name=r.displayName()==null?t.getDisplayName():r.displayName().trim();String description=r.description()==null?t.getDescription():r.description();String currency=r.currency()==null?t.getCurrency():PayrollEmployeeService.currency(r.currency());PayFrequency frequency=r.payFrequency()==null?t.getPayFrequency():r.payFrequency();SalaryTemplateStatus status=r.status()==null?t.getStatus():r.status();var from=r.effectiveFrom()==null?t.getEffectiveFrom():r.effectiveFrom();var to=r.effectiveTo()==null?t.getEffectiveTo():r.effectiveTo();validateDates(from,to);t.setDisplayName(name);t.setDescription(description);t.setCurrency(currency);t.setPayFrequency(frequency);t.setStatus(status);t.setEffectiveFrom(from);t.setEffectiveTo(to);if(r.components()!=null)replaceComponents(t,r.components());return response(templates.saveAndFlush(t));}
 @Transactional public SalaryTemplateResponse deactivate(String raw){scope.locked();SalaryTemplate t=find(raw);t.setStatus(SalaryTemplateStatus.INACTIVE);return response(templates.saveAndFlush(t));}
 @Transactional public ProfileResponse assign(String rawTemplate,String employeeCode,AssignSalaryTemplate r){scope.locked();SalaryTemplate t=find(rawTemplate);if(t.getStatus()!=SalaryTemplateStatus.ACTIVE)throw new PayrollException(409,"Inactive salary template cannot be assigned");SalaryTemplateVersion v=versions.findByTemplateIdAndVersionNumber(t.getId(),r.versionNumber()).orElseThrow(()->new PayrollException(404,"Salary template version not found"));if(v.getStatus()!=SalaryTemplateVersionStatus.ACTIVE)throw new PayrollException(409,"Inactive salary template version cannot be assigned");if(r.effectiveFrom().isBefore(v.getEffectiveFrom())||(v.getEffectiveTo()!=null&&r.effectiveFrom().isAfter(v.getEffectiveTo())))throw new PayrollException(409,"Assignment date is outside template version effective dates");if(r.effectiveTo()!=null&&r.effectiveTo().isBefore(r.effectiveFrom()))throw new PayrollException(400,"effectiveTo cannot precede effectiveFrom");if(v.getEffectiveTo()!=null&&(r.effectiveTo()==null||r.effectiveTo().isAfter(v.getEffectiveTo())))throw new PayrollException(409,"Assignment effective dates exceed template version");return compensation.createFromTemplate(employeeCode,r.profileKey(),r.effectiveFrom(),r.effectiveTo(),v);}
 private void apply(SalaryTemplate t,String name,String description,String currency,PayFrequency frequency,SalaryTemplateStatus status,java.time.LocalDate from,java.time.LocalDate to,List<TemplateComponentRequest>items){t.setDisplayName(name.trim());t.setDescription(description);t.setCurrency(PayrollEmployeeService.currency(currency));t.setPayFrequency(frequency);t.setStatus(status);t.setEffectiveFrom(from);t.setEffectiveTo(to);replaceComponents(t,items);}
 private void replaceComponents(SalaryTemplate t,List<TemplateComponentRequest>items){if(items==null||items.isEmpty())throw new PayrollException(400,"Salary template requires components");t.getComponents().clear();if(t.getId()!=null)templates.flush();Set<String>seen=new HashSet<>();for(TemplateComponentRequest item:items){String key=ComponentDefinitionService.key(item.componentKey());if(!seen.add(key))throw new PayrollException(400,"Duplicate template component");ComponentDefinition d=definitions.findByWorkspaceIdAndComponentKey(scope.context().workspaceId(),key).orElseThrow(()->new PayrollException(404,"Compensation component not found"));if(d.getStatus()!=ComponentStatus.ACTIVE)throw new PayrollException(409,"Inactive compensation component cannot be configured");validateValue(d,item.value());SalaryTemplateComponent c=new SalaryTemplateComponent();c.setTemplate(t);c.setDefinition(d);c.setValue(item.value().setScale(4,RoundingMode.UNNECESSARY));t.getComponents().add(c);}}
 private void createInitialVersion(SalaryTemplate t){SalaryTemplateVersion version=new SalaryTemplateVersion();version.setTemplate(t);version.setVersionNumber(1);version.setCurrency(t.getCurrency());version.setPayFrequency(t.getPayFrequency());version.setStatus(t.getStatus()==SalaryTemplateStatus.ACTIVE?SalaryTemplateVersionStatus.ACTIVE:SalaryTemplateVersionStatus.INACTIVE);version.setEffectiveFrom(t.getEffectiveFrom());version.setEffectiveTo(t.getEffectiveTo());int sequence=0;for(SalaryTemplateComponent item:t.getComponents()){SalaryTemplateVersionComponent component=new SalaryTemplateVersionComponent();component.setVersion(version);component.setDefinition(item.getDefinition());component.setComponentKey(item.getDefinition().getComponentKey());component.setValue(item.getValue());component.setDisplaySequence(sequence++);version.getComponents().add(component);}versions.saveAndFlush(version);}
 private void validateValue(ComponentDefinition d,BigDecimal value){if(value==null||value.signum()<0||value.scale()>4||value.precision()-value.scale()>15)throw new PayrollException(400,"Component value is invalid");if(d.getAmountType()==AmountType.PERCENTAGE&&value.compareTo(new BigDecimal("100"))>0)throw new PayrollException(400,"Percentage cannot exceed 100");}
 private SalaryTemplate find(String raw){return templates.findByWorkspaceIdAndTemplateKey(scope.context().workspaceId(),key(raw)).orElseThrow(()->new PayrollException(404,"Salary template not found"));}
 private void validateDates(java.time.LocalDate from,java.time.LocalDate to){if(to!=null&&to.isBefore(from))throw new PayrollException(400,"effectiveTo cannot precede effectiveFrom");}
 static String key(String raw){String key=raw==null?"":raw.trim().toUpperCase(Locale.ROOT);if(!key.matches("^[A-Z0-9][A-Z0-9._-]{0,63}$"))throw new PayrollException(400,"Invalid salary template key");return key;}
 private SalaryTemplateResponse response(SalaryTemplate t){var items=t.getComponents().stream().sorted(Comparator.comparing(c->c.getDefinition().getComponentKey())).map(c->{var d=c.getDefinition();return new TemplateComponentResponse(d.getComponentKey(),d.getDisplayName(),d.getCategory(),d.getAmountType(),d.getOccurrenceType(),d.getTaxability(),c.getValue());}).toList();return new SalaryTemplateResponse(t.getTemplateKey(),t.getDisplayName(),t.getDescription(),t.getCurrency(),t.getPayFrequency(),t.getStatus(),t.getEffectiveFrom(),t.getEffectiveTo(),items,t.getCreatedAt(),t.getUpdatedAt());}
}
