package com.lexorion.platform.auth;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
import com.jayway.jsonpath.JsonPath;
import com.lexorion.core.auth.repository.RefreshTokenRepository;
import com.lexorion.core.user.entity.*;
import com.lexorion.core.user.repository.UserRepository;
import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.http.MediaType;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.test.web.servlet.*;

@SpringBootTest @AutoConfigureMockMvc class AuthenticationSessionIntegrationTest{
 @Autowired MockMvc mvc;@Autowired UserRepository users;@Autowired RefreshTokenRepository tokens;@Autowired PasswordEncoder passwords;private User user;
 @BeforeEach void setup(){tokens.deleteAll();users.deleteAll();user=new User();user.setEmail("session@test.example");user.setFirstName("Session");user.setLastName("Test");user.setPasswordHash(passwords.encode("correct-password"));user.setStatus(UserStatus.ACTIVE);user=users.saveAndFlush(user);}
 @Test void rotationReuseRevokesTheEntireTokenFamily()throws Exception{String first=login().refresh();MvcResult rotated=mvc.perform(post("/api/platform/auth/refresh").contentType(MediaType.APPLICATION_JSON).content("{\"refreshToken\":\""+first+"\"}")).andExpect(status().isOk()).andReturn();String second=JsonPath.read(rotated.getResponse().getContentAsString(),"$.refreshToken");assertThat(second).isNotEqualTo(first);mvc.perform(post("/api/platform/auth/refresh").contentType(MediaType.APPLICATION_JSON).content("{\"refreshToken\":\""+first+"\"}")).andExpect(status().isUnauthorized());assertThat(tokens.findByUserIdAndRevokedFalse(user.getId())).isEmpty();mvc.perform(post("/api/platform/auth/refresh").contentType(MediaType.APPLICATION_JSON).content("{\"refreshToken\":\""+second+"\"}")).andExpect(status().isUnauthorized());}
 @Test void authenticatedUserCanRevokeEverySession()throws Exception{Tokens first=login(),second=login();assertThat(tokens.findByUserIdAndRevokedFalse(user.getId())).hasSize(2);mvc.perform(post("/api/platform/auth/sessions/revoke-all").header("Authorization","Bearer "+first.access())).andExpect(status().isNoContent());assertThat(tokens.findByUserIdAndRevokedFalse(user.getId())).isEmpty();mvc.perform(post("/api/platform/auth/refresh").contentType(MediaType.APPLICATION_JSON).content("{\"refreshToken\":\""+second.refresh()+"\"}")).andExpect(status().isUnauthorized());}
 @Test void horizonHostsReceiveHttpOnlySharedRefreshCookieWithoutRefreshTokenInBody()throws Exception{MvcResult login=mvc.perform(post("/api/core/auth/login").header("Host","admin.horizon.lexorion.in").contentType(MediaType.APPLICATION_JSON).content("{\"email\":\"session@test.example\",\"password\":\"correct-password\"}")).andExpect(status().isOk()).andReturn();String setCookie=login.getResponse().getHeader("Set-Cookie");assertThat(setCookie).contains("lexorion_refresh=").contains("Domain=.horizon.lexorion.in").contains("HttpOnly").contains("Secure").contains("SameSite=Lax");assertThat(login.getResponse().getContentAsString()).doesNotContain("refreshToken\":\"");String refresh=setCookie.substring(setCookie.indexOf('=')+1,setCookie.indexOf(';'));MvcResult rotated=mvc.perform(post("/api/core/auth/refresh").header("Host","horizon.lexorion.in").cookie(new jakarta.servlet.http.Cookie("lexorion_refresh",refresh)).contentType(MediaType.APPLICATION_JSON).content("{}")).andExpect(status().isOk()).andReturn();assertThat(rotated.getResponse().getHeader("Set-Cookie")).contains("HttpOnly");assertThat(rotated.getResponse().getContentAsString()).doesNotContain("refreshToken\":\"");}
 @Test void invalidSharedCookieIsExpired()throws Exception{MvcResult result=mvc.perform(post("/api/core/auth/refresh").header("Host","horizon.lexorion.in").cookie(new jakarta.servlet.http.Cookie("lexorion_refresh","invalid")).contentType(MediaType.APPLICATION_JSON).content("{}")).andExpect(status().isUnauthorized()).andReturn();assertThat(result.getResponse().getHeader("Set-Cookie")).contains("lexorion_refresh=").contains("Max-Age=0").contains("HttpOnly").contains("Domain=.horizon.lexorion.in");}
 private Tokens login()throws Exception{MvcResult result=mvc.perform(post("/api/platform/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"email\":\"session@test.example\",\"password\":\"correct-password\"}")).andExpect(status().isOk()).andReturn();String body=result.getResponse().getContentAsString();return new Tokens(JsonPath.read(body,"$.accessToken"),JsonPath.read(body,"$.refreshToken"));}
 private record Tokens(String access,String refresh){}
}
