package com.lexorion.payroll.domain;
import jakarta.persistence.*;import java.math.BigDecimal;import java.time.*;import java.util.UUID;import lombok.*;import org.hibernate.annotations.Check;import org.hibernate.annotations.UuidGenerator;
@Entity@Check(constraints="amount <> 0")@Table(name="payroll_ledger_entries",uniqueConstraints=@UniqueConstraint(name="uk_payroll_ledger_workspace_source",columnNames={"workspace_id","source_reference"}),indexes={@Index(name="idx_payroll_ledger_employee_period",columnList="workspace_id,payroll_employee_id,period_end"),@Index(name="idx_payroll_ledger_pay_run",columnList="workspace_id,pay_run_id")})
@Getter@NoArgsConstructor public class PayrollLedgerEntry{
 @Id@UuidGenerator private UUID id;@ManyToOne(fetch=FetchType.LAZY,optional=false)@JoinColumn(name="workspace_id",nullable=false,updatable=false)private PayrollWorkspace workspace;@ManyToOne(fetch=FetchType.LAZY,optional=false)@JoinColumn(name="payroll_employee_id",nullable=false,updatable=false)private PayrollEmployee payrollEmployee;@ManyToOne(fetch=FetchType.LAZY,optional=false)@JoinColumn(name="pay_run_id",nullable=false,updatable=false)private PayRun payRun;
 @Column(name="period_start",nullable=false,updatable=false)private LocalDate periodStart;@Column(name="period_end",nullable=false,updatable=false)private LocalDate periodEnd;@Column(name="entry_date",nullable=false,updatable=false)private LocalDate entryDate;@Enumerated(EnumType.STRING)@Column(name="entry_type",nullable=false,updatable=false,length=24)private PayrollLedgerEntryType type;
 @Column(name="component_key",updatable=false,length=64)private String componentKey;@Column(name="component_name",updatable=false,length=150)private String componentName;@Column(nullable=false,updatable=false,precision=19,scale=4)private BigDecimal amount;@Column(nullable=false,updatable=false,length=3)private String currency;@Column(name="source_reference",nullable=false,updatable=false,length=220)private String sourceReference;@Enumerated(EnumType.STRING)@Column(nullable=false,updatable=false,length=16)private PayrollLedgerEntryStatus status;@Column(name="created_at",nullable=false,updatable=false)private Instant createdAt;
 public static PayrollLedgerEntry finalized(PayRun run,PayRunEmployee employee,PayrollLedgerEntryType type,String componentKey,String componentName,BigDecimal amount,String source){PayrollLedgerEntry e=new PayrollLedgerEntry();e.workspace=run.getWorkspace();e.payrollEmployee=employee.getPayrollEmployee();e.payRun=run;e.periodStart=run.getPeriodStart();e.periodEnd=run.getPeriodEnd();e.entryDate=run.getCalculationDate();e.type=type;e.componentKey=componentKey;e.componentName=componentName;e.amount=amount;e.currency=run.getCurrency();e.sourceReference=source;e.status=PayrollLedgerEntryStatus.FINALIZED;e.createdAt=Instant.now();return e;}
}
