package com.lexorion.workforce.api;
import static com.lexorion.workforce.api.ResourceDtos.*;import com.lexorion.workforce.domain.EmploymentStatus;import com.lexorion.workforce.service.*;import io.swagger.v3.oas.annotations.Parameter;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.net.URI;import java.util.List;import org.springframework.data.domain.Sort;import org.springframework.http.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.validation.annotation.Validated;import org.springframework.web.bind.annotation.*;
@RestController@Validated@RequestMapping("/api/workforce/employees")public class EmployeeController{
 private final EmployeeService service;private final SelfServiceService access;public EmployeeController(EmployeeService s,SelfServiceService a){service=s;access=a;}
 @GetMapping@PreAuthorize("hasRole('ADMIN')")public EmployeePageResponse list(@RequestParam(required=false)EmploymentStatus status,@RequestParam(required=false)@Pattern(regexp="^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$")String departmentKey,@RequestParam(required=false)@Pattern(regexp="^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$")String designationKey,@RequestParam(required=false)@Pattern(regexp="^[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?$")String reportingManagerEmployeeCode,@RequestParam(required=false)@Size(max=100)String search,@Parameter(description="Zero-based page number")@RequestParam(defaultValue="0")@Min(0)int page,@Parameter(description="Page size from 1 through 100")@RequestParam(defaultValue="20")@Min(1)@Max(100)int size,@Parameter(description="Sort field: employeeCode, firstName, lastName, email, joiningDate, or status")@RequestParam(defaultValue="employeeCode")String sort,@Parameter(description="Sort direction: ASC or DESC")@RequestParam(defaultValue="ASC")Sort.Direction direction){return service.list(status,departmentKey,designationKey,reportingManagerEmployeeCode,search,page,size,sort,direction);}
 @GetMapping("/{employeeCode}")@PreAuthorize("hasAnyRole('ADMIN','MANAGER','EMPLOYEE')")public EmployeeResponse get(@PathVariable@Pattern(regexp="^[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?$")String employeeCode){return access.permittedRead(employeeCode);}
 @GetMapping("/{employeeCode}/history")@PreAuthorize("hasRole('ADMIN')")public List<LifecycleEventResponse> history(@PathVariable String employeeCode){return service.history(employeeCode);}
 @PostMapping@PreAuthorize("hasRole('ADMIN')")public ResponseEntity<EmployeeResponse> create(@Valid@RequestBody CreateEmployee r){var v=service.create(r);return ResponseEntity.created(URI.create("/api/workforce/employees/"+v.employeeCode())).body(v);}
 @PatchMapping("/{employeeCode}")@PreAuthorize("hasRole('ADMIN')")public EmployeeResponse update(@PathVariable String employeeCode,@Valid@RequestBody UpdateEmployee r){return service.update(employeeCode,r);}
 @PutMapping("/{employeeCode}/user-mapping")@PreAuthorize("hasRole('ADMIN')")public EmployeeResponse mapUser(@PathVariable String employeeCode,@Valid@RequestBody EmployeeUserMappingRequest r){return service.mapUser(employeeCode,r.email());}
 @PostMapping("/{employeeCode}/activate")@PreAuthorize("hasRole('ADMIN')")public EmployeeResponse activate(@PathVariable String employeeCode){return service.transition(employeeCode,EmploymentStatus.ACTIVE,"ACTIVATED");}
 @PostMapping("/{employeeCode}/leave")@PreAuthorize("hasRole('ADMIN')")public EmployeeResponse leave(@PathVariable String employeeCode){return service.transition(employeeCode,EmploymentStatus.ON_LEAVE,"PLACED_ON_LEAVE");}
 @PostMapping("/{employeeCode}/suspend")@PreAuthorize("hasRole('ADMIN')")public EmployeeResponse suspend(@PathVariable String employeeCode){return service.transition(employeeCode,EmploymentStatus.SUSPENDED,"SUSPENDED");}
 @PostMapping("/{employeeCode}/resign")@PreAuthorize("hasRole('ADMIN')")public EmployeeResponse resign(@PathVariable String employeeCode){return service.transition(employeeCode,EmploymentStatus.RESIGNED,"RESIGNED");}
 @PostMapping("/{employeeCode}/terminate")@PreAuthorize("hasRole('ADMIN')")public EmployeeResponse terminate(@PathVariable String employeeCode){return service.transition(employeeCode,EmploymentStatus.TERMINATED,"TERMINATED");}
}
