package com.lexorion.workforce.api;
import com.fasterxml.jackson.annotation.JsonSetter;import com.lexorion.workforce.domain.*;import jakarta.validation.constraints.*;import java.time.*;import java.util.UUID;
public final class ResourceDtos {private ResourceDtos(){}
 public record CreateReference(@NotBlank@Pattern(regexp="^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$")String key,@NotBlank@Size(max=150)String name,@Pattern(regexp="^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$")String parentDepartmentKey,@Null UUID organizationId,@Null UUID workspaceId,@Null UUID productId,@Null UUID planId,@Null UUID entitlementId,@Null UUID departmentId,@Null UUID designationId){}
 public static final class UpdateReference {private String name;private ActiveStatus status;private String parentDepartmentKey;private boolean parentDepartmentKeyPresent;@Null private UUID organizationId;@Null private UUID workspaceId;@Null private UUID departmentId;@Null private UUID designationId;
  @Size(min=1,max=150)public String name(){return name;}public void setName(String v){name=v;}public ActiveStatus status(){return status;}public void setStatus(ActiveStatus v){status=v;}@Pattern(regexp="^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$")public String parentDepartmentKey(){return parentDepartmentKey;}@JsonSetter("parentDepartmentKey")public void setParentDepartmentKey(String v){parentDepartmentKey=v;parentDepartmentKeyPresent=true;}public boolean parentDepartmentKeyPresent(){return parentDepartmentKeyPresent;}public UUID organizationId(){return organizationId;}public void setOrganizationId(UUID v){organizationId=v;}public UUID workspaceId(){return workspaceId;}public void setWorkspaceId(UUID v){workspaceId=v;}public UUID departmentId(){return departmentId;}public void setDepartmentId(UUID v){departmentId=v;}public UUID designationId(){return designationId;}public void setDesignationId(UUID v){designationId=v;}}
 public record Reference(String key,String name,ActiveStatus status,String parentDepartmentKey){public static Reference from(Department d){return new Reference(d.getKey(),d.getName(),d.getStatus(),d.getParent()==null?null:d.getParent().getKey());}public static Reference from(Designation d){return new Reference(d.getKey(),d.getName(),d.getStatus(),null);}}
 public record CreateEmployee(@NotBlank@Pattern(regexp="^[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?$")String employeeCode,@NotBlank@Size(max=100)String firstName,@Size(max=100)String middleName,@NotBlank@Size(max=100)String lastName,@NotBlank@Size(max=256)String workEmail,@Pattern(regexp="^$|^\\+?[0-9 ()-]{7,30}$")String phone,@NotNull@PastOrPresent LocalDate joiningDate,EmploymentStatus status,@Pattern(regexp="^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$")String departmentKey,@Pattern(regexp="^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$")String designationKey,@Pattern(regexp="^[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?$")String reportingManagerEmployeeCode,@Null UUID organizationId,@Null UUID workspaceId,@Null UUID productId,@Null UUID planId,@Null UUID entitlementId,@Null UUID employeeId,@Null UUID employeeUuid,@Null UUID departmentId,@Null UUID designationId,@Null UUID userId,@Null UUID userUuid){}
 public static final class UpdateEmployee {private String firstName,middleName,lastName,workEmail,phone,departmentKey,designationKey,reportingManagerEmployeeCode;private LocalDate joiningDate;@Null private EmploymentStatus status;private boolean reportingManagerPresent;@Null private UUID organizationId,workspaceId,productId,planId,entitlementId,employeeId,employeeUuid,departmentId,designationId,userId,userUuid;
  @Size(min=1,max=100)public String firstName(){return firstName;}public void setFirstName(String v){firstName=v;}@Size(max=100)public String middleName(){return middleName;}public void setMiddleName(String v){middleName=v;}@Size(min=1,max=100)public String lastName(){return lastName;}public void setLastName(String v){lastName=v;}@Size(max=256)public String workEmail(){return workEmail;}public void setWorkEmail(String v){workEmail=v;}@Pattern(regexp="^$|^\\+?[0-9 ()-]{7,30}$")public String phone(){return phone;}public void setPhone(String v){phone=v;}@PastOrPresent public LocalDate joiningDate(){return joiningDate;}public void setJoiningDate(LocalDate v){joiningDate=v;}public EmploymentStatus status(){return status;}public void setStatus(EmploymentStatus v){status=v;}@Pattern(regexp="^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$")public String departmentKey(){return departmentKey;}public void setDepartmentKey(String v){departmentKey=v;}@Pattern(regexp="^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$")public String designationKey(){return designationKey;}public void setDesignationKey(String v){designationKey=v;}@Pattern(regexp="^[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?$")public String reportingManagerEmployeeCode(){return reportingManagerEmployeeCode;}@JsonSetter("reportingManagerEmployeeCode")public void setReportingManagerEmployeeCode(String v){reportingManagerEmployeeCode=v;reportingManagerPresent=true;}public boolean reportingManagerPresent(){return reportingManagerPresent;}
  public UUID organizationId(){return organizationId;}public void setOrganizationId(UUID v){organizationId=v;}public UUID workspaceId(){return workspaceId;}public void setWorkspaceId(UUID v){workspaceId=v;}public UUID productId(){return productId;}public void setProductId(UUID v){productId=v;}public UUID planId(){return planId;}public void setPlanId(UUID v){planId=v;}public UUID entitlementId(){return entitlementId;}public void setEntitlementId(UUID v){entitlementId=v;}public UUID employeeId(){return employeeId;}public void setEmployeeId(UUID v){employeeId=v;}public UUID employeeUuid(){return employeeUuid;}public void setEmployeeUuid(UUID v){employeeUuid=v;}public UUID departmentId(){return departmentId;}public void setDepartmentId(UUID v){departmentId=v;}public UUID designationId(){return designationId;}public void setDesignationId(UUID v){designationId=v;}public UUID userId(){return userId;}public void setUserId(UUID v){userId=v;}public UUID userUuid(){return userUuid;}public void setUserUuid(UUID v){userUuid=v;}}
 public record EmployeeResponse(String employeeCode,String firstName,String middleName,String lastName,String workEmail,String phone,LocalDate joiningDate,EmploymentStatus status,String departmentKey,String designationKey,String reportingManagerEmployeeCode){public static EmployeeResponse from(Employee e){return new EmployeeResponse(e.getCode(),e.getFirstName(),e.getMiddleName(),e.getLastName(),e.getWorkEmail(),e.getPhone(),e.getJoiningDate(),e.getStatus(),e.getDepartment()==null?null:e.getDepartment().getKey(),e.getDesignation()==null?null:e.getDesignation().getKey(),e.getReportingManager()==null?null:e.getReportingManager().getCode());}}
 public record EmployeePageResponse(java.util.List<EmployeeResponse> content,int page,int size,long totalElements,int totalPages,String sort,String direction){}
 public record EmployeeUserMappingRequest(@NotBlank@Email@Size(max=254)String email){}
 public record LifecycleEventResponse(String action,EmploymentStatus previousStatus,EmploymentStatus newStatus,Instant occurredAt){public static LifecycleEventResponse from(EmployeeLifecycleEvent e){return new LifecycleEventResponse(e.getAction(),e.getPreviousStatus(),e.getNewStatus(),e.getOccurredAt());}}
 public record StructureDepartment(String departmentKey,String name,String parentDepartmentKey,ActiveStatus status){}
 public record StructureEmployee(String employeeCode,String name,String departmentKey,String designationKey,String reportingManagerEmployeeCode,EmploymentStatus status){}
 public record OrganizationStructureResponse(java.util.List<StructureDepartment> departments,java.util.List<StructureEmployee> employees){}
 public record TeamEmployee(String employeeCode,String name,String departmentKey,String designationKey,EmploymentStatus status){public static TeamEmployee from(Employee e){return new TeamEmployee(e.getCode(),e.getFirstName()+" "+e.getLastName(),e.getDepartment()==null?null:e.getDepartment().getKey(),e.getDesignation()==null?null:e.getDesignation().getKey(),e.getStatus());}}
 public record TeamResponse(java.util.List<TeamEmployee> employees){}
}
