package com.lexorion.workforce.service;
import static com.lexorion.workforce.api.ResourceDtos.*;
import com.lexorion.workforce.api.*;import com.lexorion.workforce.domain.*;import com.lexorion.workforce.repository.*;import com.lexorion.workforce.tenant.*;import java.util.*;import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.*;
@Service public class EmployeeService {
 private static final Map<EmploymentStatus,Set<EmploymentStatus>> TRANSITIONS=Map.of(
  EmploymentStatus.ACTIVE,Set.of(EmploymentStatus.ON_LEAVE,EmploymentStatus.SUSPENDED,EmploymentStatus.RESIGNED,EmploymentStatus.TERMINATED),
  EmploymentStatus.ON_LEAVE,Set.of(EmploymentStatus.ACTIVE,EmploymentStatus.TERMINATED),
  EmploymentStatus.SUSPENDED,Set.of(EmploymentStatus.ACTIVE,EmploymentStatus.TERMINATED,EmploymentStatus.RESIGNED),
  EmploymentStatus.RESIGNED,Set.of(EmploymentStatus.TERMINATED),EmploymentStatus.TERMINATED,Set.of());
 private static final Map<String,String> SORT_FIELDS=Map.of("employeeCode","code","firstName","firstName","lastName","lastName","email","workEmail","joiningDate","joiningDate","status","status");
 private final WorkspaceScope scope;private final EmployeeRepository employees;private final DepartmentRepository departments;private final DesignationRepository designations;private final EmployeeLifecycleEventRepository events;private final OrganizationChangeEventRepository organizationEvents;private final TenantAuthorityClient authority;private final AuthorityRequestContext request;
 public EmployeeService(WorkspaceScope s,EmployeeRepository e,DepartmentRepository d,DesignationRepository g,EmployeeLifecycleEventRepository v,OrganizationChangeEventRepository o,TenantAuthorityClient a,AuthorityRequestContext r){scope=s;employees=e;departments=d;designations=g;events=v;organizationEvents=o;authority=a;request=r;}
 @Transactional(readOnly=true)public EmployeePageResponse list(EmploymentStatus status,String departmentKey,String designationKey,String managerCode,String search,int page,int size,String sort,Sort.Direction direction){String property=SORT_FIELDS.get(sort);if(property==null)throw new WorkforceException(400,"Unsupported employee sort field");String term=blank(search)?null:"%"+search.trim().toLowerCase(Locale.ROOT)+"%";Sort ordering=Sort.by(direction,property);if(!property.equals("code"))ordering=ordering.and(Sort.by(Sort.Direction.ASC,"code"));Page<Employee> result=employees.search(scope.context().workspaceId(),status,normalizeOptionalKey(departmentKey),normalizeOptionalKey(designationKey),blank(managerCode)?null:normalizeCode(managerCode),term,PageRequest.of(page,size,ordering));return new EmployeePageResponse(result.getContent().stream().map(EmployeeResponse::from).toList(),result.getNumber(),result.getSize(),result.getTotalElements(),result.getTotalPages(),sort,direction.name().toLowerCase(Locale.ROOT));}
 @Transactional(readOnly=true)public EmployeeResponse get(String code){return EmployeeResponse.from(find(code));}
 @Transactional(readOnly=true)public List<LifecycleEventResponse> history(String code){Employee e=find(code);return events.findByWorkspaceIdAndEmployeeIdOrderByOccurredAtAscIdAsc(e.getWorkspace().getId(),e.getId()).stream().map(LifecycleEventResponse::from).toList();}
 @Transactional(isolation=Isolation.READ_COMMITTED)public EmployeeResponse create(CreateEmployee r){var w=scope.lockedWorkspace();String code=normalizeCode(r.employeeCode());if(employees.existsByWorkspaceIdAndCode(w.getId(),code))throw new DuplicateEmployeeCodeException();EmploymentStatus status=r.status()==null?EmploymentStatus.ACTIVE:r.status();if(status==EmploymentStatus.ACTIVE)requireCapacity(w);Employee e=new Employee();e.setWorkspace(w);e.setCode(code);e.setFirstName(name(r.firstName()));e.setMiddleName(optional(r.middleName()));e.setLastName(name(r.lastName()));e.setWorkEmail(email(r.workEmail()));e.setPhone(optional(r.phone()));e.setJoiningDate(r.joiningDate());e.setStatus(status);e.setDepartment(department(w.getId(),r.departmentKey()));e.setDesignation(designation(w.getId(),r.designationKey()));e.setReportingManager(manager(w.getId(),r.reportingManagerEmployeeCode(),code,null));employees.saveAndFlush(e);events.save(new EmployeeLifecycleEvent(w,e,null,status,"CREATED"));return EmployeeResponse.from(e);}
 @Transactional(isolation=Isolation.READ_COMMITTED)public EmployeeResponse update(String code,UpdateEmployee r){scope.lockedWorkspace();Employee e=find(code);if(r.firstName()!=null)e.setFirstName(name(r.firstName()));if(r.middleName()!=null)e.setMiddleName(optional(r.middleName()));if(r.lastName()!=null)e.setLastName(name(r.lastName()));if(r.workEmail()!=null)e.setWorkEmail(email(r.workEmail()));if(r.phone()!=null)e.setPhone(optional(r.phone()));if(r.joiningDate()!=null)e.setJoiningDate(r.joiningDate());if(r.departmentKey()!=null){String old=e.getDepartment()==null?null:e.getDepartment().getKey();e.setDepartment(department(e.getWorkspace().getId(),r.departmentKey()));audit(e,"DEPARTMENT_CHANGED",old,e.getDepartment()==null?null:e.getDepartment().getKey());}if(r.designationKey()!=null){String old=e.getDesignation()==null?null:e.getDesignation().getKey();e.setDesignation(designation(e.getWorkspace().getId(),r.designationKey()));audit(e,"DESIGNATION_CHANGED",old,e.getDesignation()==null?null:e.getDesignation().getKey());}if(r.reportingManagerPresent()){String old=e.getReportingManager()==null?null:e.getReportingManager().getCode();e.setReportingManager(manager(e.getWorkspace().getId(),r.reportingManagerEmployeeCode(),e.getCode(),e));audit(e,"REPORTING_MANAGER_CHANGED",old,e.getReportingManager()==null?null:e.getReportingManager().getCode());}return EmployeeResponse.from(employees.saveAndFlush(e));}
 @Transactional(isolation=Isolation.READ_COMMITTED)public EmployeeResponse transition(String code,EmploymentStatus target,String action){scope.lockedWorkspace();Employee e=find(code);EmploymentStatus previous=e.getStatus();if(!TRANSITIONS.getOrDefault(previous,Set.of()).contains(target))throw new InvalidLifecycleTransitionException(previous,target);if(target==EmploymentStatus.ACTIVE)requireCapacity(e.getWorkspace());else if(employees.existsByWorkspaceIdAndReportingManagerId(e.getWorkspace().getId(),e.getId()))throw new WorkforceException(409,"Employee with direct reports must be reassigned before becoming inactive");e.setStatus(target);employees.saveAndFlush(e);events.save(new EmployeeLifecycleEvent(e.getWorkspace(),e,previous,target,action));return EmployeeResponse.from(e);}
 @Transactional(isolation=Isolation.READ_COMMITTED)public EmployeeResponse mapUser(String code,String email){scope.lockedWorkspace();Employee e=find(code);var c=request.require();UUID userId;try{userId=authority.resolveUser(e.getWorkspace().getKey(),email.trim().toLowerCase(Locale.ROOT),c.token(),c.host(),c.organizationSlug());}catch(RuntimeException ex){throw new WorkforceException(403,"Platform user is not an active member of this organization");}if(employees.existsByWorkspaceIdAndPlatformUserIdAndIdNot(e.getWorkspace().getId(),userId,e.getId()))throw new WorkforceException(409,"Platform user is already mapped to another employee in this workspace");e.setPlatformUserId(userId);return EmployeeResponse.from(employees.saveAndFlush(e));}
 private void requireCapacity(WorkforceWorkspace w){long count=employees.countByWorkspaceIdAndStatus(w.getId(),EmploymentStatus.ACTIVE);if(count>=Integer.MAX_VALUE)throw new EmployeeLimitExceededException();var c=request.require();try{authority.requireEmployeeLimit(w.getKey(),(int)count+1,c.token(),c.host(),c.organizationSlug());}catch(RuntimeException ex){throw new EmployeeLimitExceededException();}}
 private Employee find(String code){return employees.findByWorkspaceIdAndCode(scope.context().workspaceId(),normalizeCode(code)).orElseThrow(EmployeeNotFoundException::new);}
 private Department department(UUID w,String k){if(blank(k))return null;return departments.findByWorkspaceIdAndKey(w,k.trim().toLowerCase(Locale.ROOT)).filter(d->d.getStatus()==ActiveStatus.ACTIVE).orElseThrow(InactiveDepartmentException::new);}
 private Designation designation(UUID w,String k){if(blank(k))return null;return designations.findByWorkspaceIdAndKey(w,k.trim().toLowerCase(Locale.ROOT)).filter(d->d.getStatus()==ActiveStatus.ACTIVE).orElseThrow(InactiveDesignationException::new);}
 private Employee manager(UUID w,String raw,String employeeCode,Employee employee){if(blank(raw))return null;String code=normalizeCode(raw);if(code.equals(employeeCode))throw new WorkforceException(409,"Employee cannot report to self");Employee value=employees.findByWorkspaceIdAndCode(w,code).filter(e->e.getStatus()==EmploymentStatus.ACTIVE).orElseThrow(()->new WorkforceException(400,"Reporting manager is inactive or unavailable in this workspace"));Set<UUID> seen=new HashSet<>();for(Employee p=value;p!=null;p=p.getReportingManager()){if(!seen.add(p.getId())||(employee!=null&&p.getId().equals(employee.getId())))throw new WorkforceException(409,"Reporting manager cycle rejected");}return value;}
 private void audit(Employee e,String action,String from,String to){organizationEvents.save(new OrganizationChangeEvent(e.getWorkspace(),"EMPLOYEE",e.getCode(),action,from,to));}
 private static String normalizeCode(String v){if(v==null)return "";return v.trim().toUpperCase(Locale.ROOT);}private static String normalizeOptionalKey(String v){return blank(v)?null:v.trim().toLowerCase(Locale.ROOT);}private static String email(String v){String value=v.trim().toLowerCase(Locale.ROOT);if(value.length()>254||!value.matches("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$"))throw new WorkforceException(400,"Work email is malformed");return value;}private static String name(String v){String n=v.trim();if(n.isEmpty())throw new WorkforceException(400,"Name must not be blank");return n;}private static String optional(String v){return blank(v)?null:v.trim();}private static boolean blank(String v){return v==null||v.isBlank();}
}
