package com.lexorion.payroll.api;
import com.lexorion.payroll.domain.*;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.math.BigDecimal;import java.time.LocalDate;import java.util.*;
public final class CompensationDtos {
 private CompensationDtos() {}
 public record CreateComponent(@NotBlank String componentKey,@NotBlank@Size(max=150)String displayName,@NotNull ComponentCategory category,@NotNull AmountType amountType,@NotNull OccurrenceType occurrenceType,@NotNull Taxability taxability,@NotNull ComponentStatus status,@Null UUID organizationId,@Null UUID workspaceId,@Null UUID userId,@Null UUID componentId,@Null String role){}
 public record UpdateComponent(@Size(min=1,max=150)String displayName,ComponentStatus status,@Null ComponentCategory category,@Null AmountType amountType,@Null OccurrenceType occurrenceType,@Null Taxability taxability,@Null UUID organizationId,@Null UUID workspaceId,@Null UUID userId,@Null UUID componentId,@Null String role){}
 public record ComponentResponse(String componentKey,String displayName,ComponentCategory category,AmountType amountType,OccurrenceType occurrenceType,Taxability taxability,ComponentStatus status){public static ComponentResponse from(ComponentDefinition d){return new ComponentResponse(d.getComponentKey(),d.getDisplayName(),d.getCategory(),d.getAmountType(),d.getOccurrenceType(),d.getTaxability(),d.getStatus());}}
 public record CreateProfile(@NotBlank String profileKey,@NotBlank@Pattern(regexp="^[A-Z]{3}$")String currency,@NotNull LocalDate effectiveFrom,LocalDate effectiveTo,@NotNull CompensationProfileStatus status,@NotEmpty List<@Valid CreateAssignment>components,@Null UUID organizationId,@Null UUID workspaceId,@Null UUID userId,@Null UUID employeeId,@Null UUID payrollEmployeeId,@Null UUID profileId,@Null String role){}
 public record CreateAssignment(@NotBlank String componentKey,@NotNull@DecimalMin("0.0000")@Digits(integer=15,fraction=4)BigDecimal value,@Null String currency,@Null ComponentCategory category,@Null AmountType amountType,@Null OccurrenceType occurrenceType,@Null Taxability taxability,@Null UUID componentId,@Null UUID assignmentId){}
 public record AssignmentResponse(String componentKey,String displayName,ComponentCategory category,AmountType amountType,PayFrequency frequency,OccurrenceType occurrenceType,Taxability taxability,BigDecimal value){}
 public record ProfileResponse(String employeeCode,String profileKey,String sourceTemplateKey,Integer sourceTemplateVersion,String currency,LocalDate effectiveFrom,LocalDate effectiveTo,CompensationProfileStatus status,List<AssignmentResponse>components){}
}
