package com.lexorion.payroll;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import com.lexorion.payroll.domain.*;import com.lexorion.payroll.entitlement.PayrollProcessingEntitlementGate;import com.lexorion.payroll.repository.*;import com.lexorion.payroll.tenant.*;import com.lexorion.payroll.workforce.*;import java.math.BigDecimal;import java.nio.charset.StandardCharsets;import java.util.*;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.http.MediaType;import org.springframework.test.context.bean.override.mockito.MockitoBean;import org.springframework.test.web.servlet.*;

@SpringBootTest@AutoConfigureMockMvc class PayrollFoundationIntegrationTest{
 static final UUID A=UUID.fromString("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),B=UUID.fromString("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),ALPHA=UUID.fromString("11111111-1111-1111-1111-111111111111"),BETA=UUID.fromString("22222222-2222-2222-2222-222222222222");
 @Autowired MockMvc mvc;@Autowired PayrollLedgerEntryRepository ledger;@Autowired SalaryTemplateRepository templates;@Autowired PayRunEmployeeRepository runEmployees;@Autowired PayRunRepository runs;@Autowired CalculationLineRepository lines;@Autowired CalculationRepository calculations;@Autowired ComponentAssignmentRepository assignments;@Autowired CompensationProfileRepository profiles;@Autowired ComponentDefinitionRepository definitions;@Autowired PayrollEmployeeRepository employees;@Autowired PayrollWorkspaceRepository workspaces;
 @MockitoBean PayrollAuthorityClient authority;@MockitoBean WorkforceEmployeeVerifier workforce;@MockitoBean PayrollProcessingEntitlementGate entitlement;
 @BeforeEach void setup(){cleanup();when(authority.validate(anyString(),anyString(),any(),nullable(String.class))).thenAnswer(i->context(i.getArgument(0),i.getArgument(1),i.getArgument(3)));when(workforce.verify(anyString(),any())).thenAnswer(i->new WorkforceEmployeeVerifier.Verification(i.getArgument(0),true,WorkforceEmploymentStatus.ACTIVE));doNothing().when(entitlement).requireProcessing(any());}
 @AfterEach void cleanup(){ledger.deleteAll();runEmployees.deleteAll();runs.deleteAll();lines.deleteAll();calculations.deleteAll();assignments.deleteAll();profiles.deleteAll();templates.deleteAll();definitions.deleteAll();employees.deleteAll();workspaces.deleteAll();}

 @Test void templateAssignmentCreatesStableCompensationSnapshotAndRejectsInactiveTemplate()throws Exception{employee("a","alpha","owner","EMP-1");component("a","alpha","owner","BASE","Base","EARNING");component("a","alpha","owner","TAX","Tax","DEDUCTION");template("a","alpha","owner","STANDARD","1000","10").andExpect(status().isCreated()).andExpect(jsonPath("$.components.length()").value(2)).andExpect(jsonPath("$.id").doesNotExist());assign("a","alpha","admin","STANDARD","EMP-1","P-1").andExpect(status().isCreated()).andExpect(jsonPath("$.sourceTemplateKey").value("STANDARD")).andExpect(jsonPath("$.components[0].value").value(1000.0));request(patch("/api/payroll/salary-templates/STANDARD").contentType(MediaType.APPLICATION_JSON).content("{\"displayName\":\"Changed\",\"components\":[{\"componentKey\":\"BASE\",\"value\":2000},{\"componentKey\":\"TAX\",\"value\":20}]}"),"a","alpha","owner").andExpect(status().isOk());request(get("/api/payroll/employees/EMP-1/compensation/P-1"),"a","alpha","owner").andExpect(jsonPath("$.components[0].value").value(1000.0)).andExpect(jsonPath("$.components[1].value").value(10.0));request(delete("/api/payroll/salary-templates/STANDARD"),"a","alpha","owner").andExpect(jsonPath("$.status").value("INACTIVE"));assign("a","alpha","owner","STANDARD","EMP-1","P-2").andExpect(status().isConflict());}

 @Test void templateAdministrationIsRoleAndWorkspaceScopedAndRejectsInjection()throws Exception{component("a","alpha","owner","BASE","Base","EARNING");template("a","alpha","owner","STANDARD","1000",null).andExpect(status().isCreated());request(get("/api/payroll/salary-templates/STANDARD"),"b","beta","owner").andExpect(status().isNotFound());request(get("/api/payroll/salary-templates"),"a","alpha","manager").andExpect(status().isForbidden());request(get("/api/payroll/salary-templates"),"a","alpha","member").andExpect(status().isForbidden());request(post("/api/payroll/salary-templates").contentType(MediaType.APPLICATION_JSON).content(templateJson("INJECT","1",null).replace("}",",\"workspaceId\":\""+B+"\"}")),"a","alpha","owner").andExpect(status().isBadRequest());template("a","alpha","owner","STANDARD","1",null).andExpect(status().isConflict());}
 @Test void templateVersionsAreScopedValidatedAndHistorical()throws Exception{component("a","alpha","owner","BASE","Base","EARNING");request(post("/api/payroll/salary-templates").contentType(MediaType.APPLICATION_JSON).content(templateJson("VERSIONED","1000",null).replace("\"components\"","\"effectiveTo\":\"2026-12-31\",\"components\"")),"a","alpha","owner").andExpect(status().isCreated());request(get("/api/payroll/salary-templates/VERSIONED/versions"),"a","alpha","owner").andExpect(jsonPath("$[0].versionNumber").value(1)).andExpect(jsonPath("$[0].status").value("ACTIVE"));request(get("/api/payroll/salary-templates/VERSIONED/versions"),"b","beta","owner").andExpect(status().isNotFound());request(post("/api/payroll/salary-templates/VERSIONED/versions").contentType(MediaType.APPLICATION_JSON).content("{\"currency\":\"USD\",\"payFrequency\":\"MONTHLY\",\"status\":\"DRAFT\",\"effectiveFrom\":\"2027-01-01\",\"components\":[{\"componentKey\":\"BASE\",\"value\":1200,\"displaySequence\":0}]}"),"a","alpha","owner").andExpect(status().isCreated()).andExpect(jsonPath("$.versionNumber").value(2)).andExpect(jsonPath("$.components[0].componentKey").value("BASE"));request(patch("/api/payroll/salary-templates/VERSIONED/versions/2").contentType(MediaType.APPLICATION_JSON).content("{\"components\":[{\"componentKey\":\"BASE\",\"value\":1300}] ,\"effectiveFrom\":\"2027-01-01\"}"),"a","alpha","owner").andExpect(status().isOk()).andExpect(jsonPath("$.components[0].value").value(1300.0));request(patch("/api/payroll/salary-templates/VERSIONED/versions/2").contentType(MediaType.APPLICATION_JSON).content("{\"components\":[{\"componentKey\":\"BASE\",\"value\":1400},{\"componentKey\":\"BASE\",\"value\":1500}]}"),"a","alpha","owner").andExpect(status().isBadRequest());request(post("/api/payroll/salary-templates/VERSIONED/versions/2/activate"),"a","alpha","owner").andExpect(status().isOk()).andExpect(jsonPath("$.status").value("ACTIVE"));request(patch("/api/payroll/salary-templates/VERSIONED/versions/2").contentType(MediaType.APPLICATION_JSON).content("{\"components\":[{\"componentKey\":\"BASE\",\"value\":1500}]}"),"a","alpha","owner").andExpect(status().isConflict());request(get("/api/payroll/salary-templates/VERSIONED/versions/1"),"a","alpha","owner").andExpect(jsonPath("$.components[0].value").value(1000.0));}

 @Test void finalizationAtomicallyCreatesBalancedImmutableLedgerAndPayslipSnapshot()throws Exception{employee("a","alpha","owner","EMP-1");component("a","alpha","owner","BASE","Base","EARNING");component("a","alpha","owner","TAX","Tax","DEDUCTION");template("a","alpha","owner","STANDARD","1000","10");assign("a","alpha","owner","STANDARD","EMP-1","P-1");run("a","alpha","owner","RUN-1");request(post("/api/payroll/pay-runs/RUN-1/employees").contentType(MediaType.APPLICATION_JSON).content("{\"employeeCode\":\"EMP-1\"}"),"a","alpha","owner").andExpect(status().isCreated());request(post("/api/payroll/pay-runs/RUN-1/process"),"a","alpha","owner").andExpect(jsonPath("$.status").value("CALCULATED")).andExpect(jsonPath("$.netTotal").value(900.0));request(get("/api/payroll/employees/EMP-1/payslips"),"a","alpha","owner").andExpect(jsonPath("$.length()").value(0));request(post("/api/payroll/pay-runs/RUN-1/finalize"),"a","alpha","admin").andExpect(jsonPath("$.status").value("FINALIZED"));assertThat(ledger.count()).isEqualTo(3);assertThat(ledger.findAll()).extracting(e->e.getType()).containsExactlyInAnyOrder(PayrollLedgerEntryType.EARNING,PayrollLedgerEntryType.DEDUCTION,PayrollLedgerEntryType.NET_PAY);assertThat(ledger.findAll().stream().map(e->e.getAmount()).reduce(java.math.BigDecimal.ZERO,java.math.BigDecimal::add)).isEqualByComparingTo("0.0000");request(get("/api/payroll/employees/EMP-1/ledger?payRunKey=RUN-1"),"a","alpha","owner").andExpect(status().isOk()).andExpect(jsonPath("$.length()").value(3)).andExpect(jsonPath("$[0].id").doesNotExist());request(get("/api/payroll/employees/EMP-1/payslips/RUN-1"),"a","alpha","owner").andExpect(jsonPath("$.grossAmount").value(1000.0)).andExpect(jsonPath("$.deductionAmount").value(100.0)).andExpect(jsonPath("$.netAmount").value(900.0)).andExpect(jsonPath("$.earnings[0].componentKey").value("BASE"));request(patch("/api/payroll/salary-templates/STANDARD").contentType(MediaType.APPLICATION_JSON).content("{\"components\":[{\"componentKey\":\"BASE\",\"value\":5000},{\"componentKey\":\"TAX\",\"value\":20}]}"),"a","alpha","owner");request(get("/api/payroll/employees/EMP-1/payslips/RUN-1"),"a","alpha","owner").andExpect(jsonPath("$.netAmount").value(900.0));request(post("/api/payroll/pay-runs/RUN-1/finalize"),"a","alpha","owner").andExpect(status().isConflict());assertThat(ledger.count()).isEqualTo(3);request(get("/api/payroll/employees/EMP-1/ledger"),"b","beta","owner").andExpect(status().isNotFound());request(get("/api/payroll/employees/EMP-1/payslips"),"a","alpha","manager").andExpect(status().isForbidden());}

 @Test void ledgerFailureRollsBackFinalizedState()throws Exception{employee("a","alpha","owner","EMP-1");component("a","alpha","owner","BASE","Base","EARNING");template("a","alpha","owner","STANDARD","1000",null);assign("a","alpha","owner","STANDARD","EMP-1","P-1");run("a","alpha","owner","RUN-ROLLBACK");request(post("/api/payroll/pay-runs/RUN-ROLLBACK/employees").contentType(MediaType.APPLICATION_JSON).content("{\"employeeCode\":\"EMP-1\"}"),"a","alpha","owner").andExpect(status().isCreated());request(post("/api/payroll/pay-runs/RUN-ROLLBACK/process"),"a","alpha","owner").andExpect(jsonPath("$.status").value("CALCULATED"));PayRun payRun=runs.findByWorkspaceIdAndPayRunKey(A,"RUN-ROLLBACK").orElseThrow();PayRunEmployee employee=runEmployees.findByPayRunIdOrderByEmployeeCodeAsc(payRun.getId()).getFirst();ledger.saveAndFlush(PayrollLedgerEntry.finalized(payRun,employee,PayrollLedgerEntryType.ADJUSTMENT,null,"Injected ledger failure",BigDecimal.ONE,"preexisting"));request(post("/api/payroll/pay-runs/RUN-ROLLBACK/finalize"),"a","alpha","owner").andExpect(status().isConflict());assertThat(runs.findByWorkspaceIdAndPayRunKey(A,"RUN-ROLLBACK").orElseThrow().getStatus()).isEqualTo(PayRunStatus.CALCULATED);assertThat(ledger.count()).isEqualTo(1);}

 private ResultActions employee(String w,String org,String token,String code)throws Exception{return request(post("/api/payroll/employees").contentType(MediaType.APPLICATION_JSON).content("{\"employeeCode\":\""+code+"\",\"status\":\"ACTIVE\",\"currency\":\"USD\",\"payFrequency\":\"MONTHLY\",\"effectiveFrom\":\"2026-01-01\"}"),w,org,token);}
 private ResultActions component(String w,String org,String token,String key,String name,String category)throws Exception{return request(post("/api/payroll/components").contentType(MediaType.APPLICATION_JSON).content("{\"componentKey\":\""+key+"\",\"displayName\":\""+name+"\",\"category\":\""+category+"\",\"amountType\":\""+(category.equals("DEDUCTION")?"PERCENTAGE":"FIXED_AMOUNT")+"\",\"occurrenceType\":\"RECURRING\",\"taxability\":\"TAXABLE\",\"status\":\"ACTIVE\"}"),w,org,token);}
 private ResultActions template(String w,String org,String token,String key,String base,String tax)throws Exception{return request(post("/api/payroll/salary-templates").contentType(MediaType.APPLICATION_JSON).content(templateJson(key,base,tax)),w,org,token);}
 private String templateJson(String key,String base,String tax){return "{\"templateKey\":\""+key+"\",\"displayName\":\"Standard\",\"description\":\"Monthly salary\",\"currency\":\"USD\",\"payFrequency\":\"MONTHLY\",\"status\":\"ACTIVE\",\"effectiveFrom\":\"2026-01-01\",\"components\":[{\"componentKey\":\"BASE\",\"value\":"+base+"}"+(tax==null?"":",{\"componentKey\":\"TAX\",\"value\":"+tax+"}")+"]}";}
 private ResultActions assign(String w,String org,String token,String template,String employee,String profile)throws Exception{return request(post("/api/payroll/salary-templates/"+template+"/employees/"+employee+"/compensation").contentType(MediaType.APPLICATION_JSON).content("{\"profileKey\":\""+profile+"\",\"versionNumber\":1,\"effectiveFrom\":\"2026-01-01\"}"),w,org,token);}
 private ResultActions run(String w,String org,String token,String key)throws Exception{return request(post("/api/payroll/pay-runs").contentType(MediaType.APPLICATION_JSON).content("{\"payRunKey\":\""+key+"\",\"periodStart\":\"2026-09-01\",\"periodEnd\":\"2026-09-30\",\"calculationDate\":\"2026-09-30\",\"currency\":\"USD\"}"),w,org,token);}
 private ResultActions request(org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder r,String w,String org,String token)throws Exception{return mvc.perform(r.header("Host","horizon.lexorion.in").header("Authorization","Bearer "+token).header("X-Lexorion-Workspace",w).header("X-Lexorion-Organization",org));}
 private TrustedPayrollContext context(String w,String token,String org){if((!w.equals("a")&&!w.equals("b"))||!org.equals(w.equals("a")?"alpha":"beta"))throw new IllegalArgumentException();return new TrustedPayrollContext(w.equals("a")?A:B,w,w.equals("a")?ALPHA:BETA,org,token.contains("manager")?"MANAGER":token.contains("member")?"EMPLOYEE":token.contains("admin")?"ADMIN":"ADMIN",UUID.nameUUIDFromBytes((w+":"+token).getBytes(StandardCharsets.UTF_8)));}
}
